"use client"
import Header from "../components/Header";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Inter, Open_Sans } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const sans = Open_Sans({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata = {
  title: "Rainbow Academic Homes",
  description: "Generated by create next app",
  icon: "/assets/logo.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const handleToggle = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="en">
      <body className={sans.className}>
        <Header />
        <Navbar />
      <main className={`${isMenuOpen ? '-z-10':"-z-10" }`}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
